TITLE: 'repr_table4_3dpw_model'
DEBUG: false
DEBUG_FREQ: 5
LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'exp'
OUTPUT_DIR: './experiments' # your path
NUM_WORKERS: 8
SEED_VALUE: 1
DATASET:
  SEQLEN: 16
LOSS:
  KP_2D_W: 300.0
  KP_3D_W: 300.0
  SHAPE_W: 0.06
  POSE_W: 60.0
  D_MOTION_LOSS_W: 0.0
  vel_or_accel_2d_weight: 10.
  vel_or_accel_3d_weight: 100.
  use_accel: False
TRAIN:
  val_epoch: 25
  BATCH_SIZE: 64
  NUM_ITERS_PER_EPOCH: 1000
#  PRETRAINED: '/mnt/SCD/VideoHMR/GLoT/experiments/Zip/29-01-2024_01-15-13_table1_3dpw_exp/model_best.pth.tar' # for testing
  RESUME: ''
  START_EPOCH: 0
  END_EPOCH: 150
  LR_PATIENCE: 10
  OVERLAP: 0.
#  DATASETS_2D:
#    - 'Insta'
  DATASETS_3D:
    - 'ThreeDPW'
    - 'MPII3D'
    - 'Human36M'
  DATASET_EVAL: 'ThreeDPW'
  GEN_LR: 0.0001
  GEN_WD: 0.0
  MOT_DISCR:
    OPTIM: 'Adam'
    LR: 0.0001
    WD: 0.0001
    MOMENTUM: 0.9
    HIDDEN_SIZE: 1024
    NUM_LAYERS: 2
    FEATURE_POOL: 'attention'
    ATT:
      LAYERS: 3
      SIZE: 1024
      DROPOUT: 0.2